Add futurevoter API endpoint
vote/turnout pull request #719
Opened 2021-03-03 17:21 UTC by benweissmann

- Adds a new endpoint for submitting FutureVoter records
- Refactors the DateSerializer a bit to handle more custom age validation, and use that to make sure FutureVoters are between 13 and 18
- Allow futurevoter.com in our CORS config

2021-03-09 18:19 UTC, ericisaiah requested changes
Various questions - some of which may be related to my missing context or Django knowledge. Hope some are helpful.

2021-03-09 18:19 UTC, ericisaiah commented on app/common/utils/serializers.py
> +        return 1900
Is there a reason this is a function vs a constant?

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/migrations/0001_initial.py
> +            fields=[
I know it's not on futurevoter.com now, but I think we should try to collect Zip code, at least. Is there a reason we're not collecting any location data about the person? @debracleaver  There may be context I'm missing.

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/migrations/0001_initial.py
> +                ('date_of_birth', models.DateField(null=True)),
I think we probably don't want to accept null values here.

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/models.py
> +        indexes = [
Is there a reason phone is not in this list of indices, even though you added created_at? I may be missing something about Django

2021-03-09 18:19 UTC, ericisaiah commented on app/common/utils/serializers.py
> +        return date.today().year - 16
I see that was in the original, but why -16 here? Don't we want -12/13?

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/serializers.py
> +        return date.today().year
Why are you overriding this?

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/serializers.py
> +    email = serializers.EmailField(required=True)
Do we need both email and phone? i.e. should we allow phone, email, or both? but not require both

2021-03-09 18:19 UTC, ericisaiah commented on app/futurevoter/serializers.py
> +    first_name = serializers.CharField(required=True)
Is there a reason we require name?

2021-03-09 18:21 UTC, benweissmann commented on app/common/utils/serializers.py
> +        return 1900
So that subclasses (like FutureVoterSerializer) can override it

2021-03-09 18:24 UTC, benweissmann commented on app/futurevoter/migrations/0001_initial.py
> +                ('date_of_birth', models.DateField(null=True)),
We always use nullable fields, because we run migrations before the code out so new columns have to be nullable or the old code will error. We *could* have non-nullable fields in brand new models like this one, but it feels weird to introduce that inconsistency (DB fields are non-nullable if they were in the first revision of the model, nullable otherwise). We enforce that this is required in the serializer rather than at the DB level

2021-03-09 18:25 UTC, benweissmann commented on app/futurevoter/models.py
> +        indexes = [
That's my bad; there shouldn't be an explicit indexes list here

2021-03-09 18:25 UTC, benweissmann commented on app/futurevoter/serializers.py
> +    first_name = serializers.CharField(required=True)
Not sure, that's a Debra question

2021-03-09 18:26 UTC, benweissmann commented on app/futurevoter/serializers.py
> +    email = serializers.EmailField(required=True)
My next branch makes email optional; Debra wants to do all outreach by SMS so we'll need a phone but not an email

2021-03-09 18:26 UTC, benweissmann commented on app/futurevoter/serializers.py
> +        return date.today().year
By default, you need to be 16 to use our tools. For this tool, you can be younger than that.

2021-03-09 18:31 UTC, ericisaiah commented on app/common/utils/serializers.py
> +        return date.today().year - 16
I thought we wanted to limit to 13 years or older

2021-03-09 18:32 UTC, benweissmann commented on app/common/utils/serializers.py
> +        return date.today().year - 16
This is in `common/utils/serializers.py` -- it's what we use to serialized DOBs across the app. We override this in the subclass in `futurevoter/serializers.py` below.

2021-03-09 19:24 UTC, ericisaiah commented on app/futurevoter/migrations/0001_initial.py
> +            fields=[
I would bet most young people at least stay in their same state, so that at least might be useful besides Zip.

2021-03-11 17:45 UTC, benweissmann commented on app/futurevoter/models.py
> +        indexes = [
Looked at this again -- I think this is correct. Django creates indexes for any field that has `db_index=True`, as well as any indexes listed here. The reason we don't set `db_index=True` on the `created_at` field in the parent `TimestampModel` is that some models want to set that index up differently (e.g. `Event` uses a composite index on `event_type, created_at`) and you can't set up a parent TimestampModel to allow subclasses to selectively disable a `db_index` (as far as i know).

2021-03-11 18:16 UTC, ericisaiah commented on app/futurevoter/serializers.py
> +        return date.today().year
Shouldn't this be 13 years ago? Not just any year?

2021-03-11 18:18 UTC, ericisaiah commented
Just responded to a few things, but I don't think anything's a blocker. The only major thing I would make sure we do is add the state field. I can't imagine we wouldn't want to at least collect that location info. But maybe file a ticket to ask Debra when she's back versus making it a blocker.

2021-03-11 19:54 UTC, benweissmann commented
@ericisaiah https://app.clubhouse.io/turnout2020/story/5537/confirm-the-fields-we-want-for-futurevoter

2021-03-11 19:56 UTC, benweissmann commented on app/futurevoter/serializers.py
> +        return date.today().year
We do a full validation below where we actually check birth date -- we can't validate the year in isolation, because we can't tell whether you're 12 or 13 based just on year number. So the validation below does the real over-18 validation, and this just makes it so a) the default validation doesn't kick in, and b) the error message to the client is "invalid year" if the year is in the future rather than "you must be 13"

2021-03-11 19:56 UTC, merged