Update Verifier with better matching logic and more metadata
vote/turnout pull request #721
Opened 2021-03-08 17:24 UTC by benweissmann

- Handle spaces in first name and missing DOB in the Verifier matching logic
- Return the address from Targetsmart so we can show that on the confirmation screen instead of echoing back the user input
- Return the last-update date from Targetsmart
- Add a new "warnings" field so we can indicate to the user that we simplified their first name or matched them without date of birth

2021-03-10 19:06 UTC, ericisaiah requested changes
Some questions and suggestions.

2021-03-10 19:06 UTC, ericisaiah commented on app/verifier/tests/test_api_views.py
> +        LOOKUP_API_ENDPOINT, {**VALID_LOOKUP, "first_name": "Barack Hussein"}
Per my trim whitespace comment above, maybe add ones to assert " Barack Hussein" gives the warning, and "Barack " does not. Unless that's covered elsewhere in tests that leading/trailing whitespace is ignored (I didn't do an exhaustive search of the tests.)

2021-03-11 17:55 UTC, benweissmann commented on app/verifier/api_views.py
> +def perform_lookup(
I think make_response should stay here because if we get another backend like L2 to use in addition to Targetsmart, then `make_response` will handle things like normalizing the result across both backends or merging the results. But definitely agree about moving the other stuff into targetsmart.py.

2021-03-11 18:05 UTC, benweissmann commented on app/verifier/api_views.py
> +        if " " in query_params["first_name"]:
good call!

2021-03-11 18:06 UTC, benweissmann commented on app/verifier/tests/test_api_views.py
> +        "last_update_date": "2021-01-21",
The `"%Y%m%d"` format is for when we're parsing the last-updated date from Targetsmart. Targetsmart returns the date as a number (?!) in the format `20210121`, but I figured it'd be easier for the frontend to handle a normal ISO date format (`"2021-01-21"`)

2021-03-11 18:20 UTC, ericisaiah commented on app/verifier/tests/test_api_views.py
> +        "last_update_date": "2021-01-21",
I may have missed it, but where does this get formatted to ISO?

2021-03-12 13:29 UTC, benweissmann commented on app/verifier/tests/test_api_views.py
> +        "last_update_date": "2021-01-21",
We set it to a python `date` object here, which uses ISO format by default when serializing: https://github.com/vote/turnout/blob/feature/verify-improvements/app/verifier/api_views.py#L65

2021-03-12 18:07 UTC, ericisaiah commented on app/verifier/tests/test_api_views.py
> +        "last_update_date": "2021-01-21",
Ah ok

2021-03-12 19:28 UTC, merged