Implement FutureVoter post-18th-birthday drip campaign
vote/turnout pull request #730
Opened 2021-04-01 19:58 UTC by benweissmann

- Add an endpoint that marks a FutureVoter as having confirmed that they registered
- Add a daily job to send a text to any FutureVoter who 1) has received the 18th-birthday text, 2) has not confirmed that they registered, 3) has not gotten a reminder text from us in at least a week, and 4) has been 18 for more than 5 weeks. This text includes the registration link, as well as a link to a not-yet-built "/confirm" page on FutureVoter. This page will make a POST request to that new endpoint that marks them as confirmed, and also show them a new-voter guide.

2021-04-05 18:08 UTC, ericisaiah requested changes
Overall looks good. Some minor things to consider.

2021-04-05 18:08 UTC, ericisaiah commented on app/futurevoter/tasks.py
> +                f"https://www.futurevoter.com/register/?{futurevoter.get_query_params()}",
See comment below renaming the `get_query_params` method, but then it might also be a good idea to add an argument for the utm_campaign, so it's like `get_register_query_params(self, campaign)` and set the `"utm_campaign": campaign`. At the moment, it's not tracking which register campaign (bday vs drip) whence a person came.

2021-04-06 14:52 UTC, benweissmann commented on app/futurevoter/tasks.py
> +    drip_cutoff = date.today() - DRIP_PROGRAM_LENGTH
Pretty arbitrary; i just picked 5 weeks and ran it by Debra. One nice thing about how we're doing this cutoff (length of time rather than tracking the number of emails we've sent) is that we can increase DRIP_PROGRAM_LENGTH in the future and it won't start emailing people who turned 18 a long time ago.

I think we'll want to analyze the distribution of (date registered - date the voter turned 18) once this is live -- we'd expect a bunch of people to register on their 18th bday when we first text them, and then spikes each week as we send them a reminder. I'd expect by week 4 or 5 we have a pretty small number of people registering because they've already gotten a lot of reminders, but if we're still seeing the fourth or fifth reminder being pretty effective then we can expand this out. The goal here is to maximize conversion while minimizing opt-outs due to people being annoyed at us texting them too many times.

2021-04-06 16:04 UTC, ericisaiah commented on app/futurevoter/tasks.py
> +    drip_cutoff = date.today() - DRIP_PROGRAM_LENGTH
Cool, love it!

2021-04-06 16:04 UTC, ericisaiah approved these changes

2021-04-07 14:36 UTC, merged