Show a disabled message for users whose own account or organization is disabled
vote/turnout pull request #732
Opened 2021-04-08 08:03 UTC by ericisaiah

Also some tests.

2021-04-08 08:09 UTC, ericisaiah commented
https://app.clubhouse.io/turnout2020/story/5385/subscribers-make-sure-that-every-user-is-associated-with-a-client

2021-04-09 14:31 UTC, benweissmann requested changes

2021-04-09 14:31 UTC, benweissmann commented on app/accounts/models/user.py
> +    def is_organization_owner(self):
Is this just a short-term thing? I think if we want to really do org owners, we should move to having a foreign key from organization to its owner

2021-04-09 14:31 UTC, benweissmann commented on app/accounts/models/user.py
> +    def is_organization_owner(self):
But i also think this is fine for now

2021-04-09 14:31 UTC, benweissmann commented on app/accounts/templates/accounts/disabled_account.html
> +                            Please contact your team admin to reactivate your account.
Can we show the billing email here so they know who the account owner is?

2021-04-09 14:31 UTC, benweissmann commented on app/manage/mixins.py
> +        if request.user.is_authenticated and (
Does this cover the VoteAmerica admin in addition to the Django admin? Not sure if ManageViewMixin is included everywhere or just the django admin

2021-04-09 17:14 UTC, ericisaiah commented on app/accounts/models/user.py
> +    def is_organization_owner(self):
Yeah, I am intentionally avoiding a migration since clients/partners/subscribers/orgs need to refactored in any case and rethought in the near term...

2021-04-09 17:15 UTC, ericisaiah commented on app/accounts/templates/accounts/disabled_account.html
> +                            Please contact your team admin to reactivate your account.
Sounds good

2021-04-09 17:16 UTC, ericisaiah commented on app/manage/mixins.py
> +        if request.user.is_authenticated and (
Yeah, that's what the test `test_disabled_account` confirms. Can you double check that?

2021-04-09 17:27 UTC, benweissmann approved these changes
Looks good

2021-04-14 01:30 UTC, ericisaiah commented
@benweissmann Could you take another look at this please? The changes to get this working were not obvious and required some digging into how two_factor overrides the built-in Django AuthenticationForm. You'll see that comment in-line, but let me know if you have any questions. We're basically doing something different than Django or two_factor expect with `User.is_active`.

Also I've added the UI to actually deactivate/reactive users. After this gets merged and deployed, I'll finally fix those orphan users so they are re-associated with their clients.

2021-04-15 21:23 UTC, benweissmann approved these changes
looks good to me!

2021-04-16 04:49 UTC, ericisaiah commented
thanks!

2021-04-16 05:27 UTC, merged