Add more instructions to registration forms
vote/turnout pull request #734
Opened 2021-04-16 13:46 UTC by benweissmann

Backend support for https://github.com/vote/voteamerica/pull/1188

This adds additional instructions that used to be provided on the frontend to the cover sheet and email for Register.

2021-04-16 18:43 UTC, ericisaiah requested changes
A few suggestions

2021-04-16 18:43 UTC, ericisaiah commented on app/register/generateform.py
> +2. Fill in box 6 (ID Number). %s
Will this insert the ID here? Minor thing but I would make this a colon versus period.

2021-04-16 18:43 UTC, ericisaiah commented on app/register/generateform.py
> +6. Mail or hand-deliver the form to the address listed below.
Maybe, "Send by mail or deliver the form in person to..."

2021-04-16 18:43 UTC, ericisaiah commented on app/register/generateform.py
> +7. If you need a stamp, you can buy one at any grocery store. Just ask the cashier.
This seems like it could be a parenthetical as a a part of step 6 (and the fewer steps the better). Perhaps also being clear that a stamp is required to mail it because sometimes people get confused if they need a stamp to mail voter stuff (even though i know in this case it's just something they're printing out). Another small thing, but just to be more inclusive: I might use 'convenience' store or something more general/common vs grocery store. Interesting research out there on distance to travel for groceries in particular: e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3701025/

So I would add something like this to step 6: "(You'll need a stamp to mail it; you can buy one at your local convenience store.)"

2021-04-16 18:43 UTC, ericisaiah commented on app/register/templates/register/email/file_notification.html
> +  <li>Box 8 is optional.</li>
Add the parenthetical here to be consistent (Race or Ethnic Group)?

2021-04-16 18:43 UTC, ericisaiah commented on app/register/templates/register/email/file_notification.html
> +  <li>Fill in box 6 (ID Number). {{ state_info.registration_nvrf_box_6 }}</li>
same commont, colon vs period

2021-04-16 18:50 UTC, benweissmann commented on app/register/generateform.py
> +2. Fill in box 6 (ID Number). %s
Nope, we insert the value of `registration_nvrf_box_6` here. We store this as a full sentence; see https://admin.voteamerica.com/manage/election/fieldinformationtype/registration_nvrf_box_6/

2021-04-16 18:50 UTC, benweissmann commented on app/register/templates/register/email/file_notification.html
> +  <li>Box 8 is optional.</li>
Let's run through this copy real quick with Debra today (have some other questions about these instructions too)

2021-04-16 18:52 UTC, ericisaiah commented on app/register/generateform.py
> +2. Fill in box 6 (ID Number). %s
Ohhh gotcha. Nevermind then.

2021-04-16 18:52 UTC, ericisaiah commented on app/register/templates/register/email/file_notification.html
> +  <li>Fill in box 6 (ID Number). {{ state_info.registration_nvrf_box_6 }}</li>
ignore

2021-04-27 19:04 UTC, ericisaiah approved these changes
looks good

2021-04-29 16:49 UTC, merged